### ISSUE TITLE
CMHTMLStrikethroughTransformer init should use the current color by default

### ISSUE THREAD

**Issue by damienrambout** [indragiek/CocoaMarkdown#1]
When initialising a `CMHTMLStrikethroughTransformer` with the convenience `init` constructor, I think it'd be better to pass `nil`(instead of black) as default color. This way, the line would get the same color (e.g. red) as the text it's striking through.

I can fork / pull request for that if you want.

**Comment by indragiek** [comment]
I agree. Feel free to send in a PR for this change!

--
Indragie Karunaratne
