### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by jamztang** [indragiek/CocoaMarkdown#10]
I noticed that the images are not being implemented in the CMAttributedStringRenderer. Is there a plan for that?

I've been trying to work on an asynchronous version and getting some progress [here](https://github.com/jamztang/CocoaMarkdown/tree/feature/remote_async_images).

**Comment by indragiek** [comment]
I didn't plan on it, but contributions are always welcome. Send a pull request if you implement it :)

**Comment by krodak** [comment]
@jamztang  - I've added fully working image support, you can check it out here:

https://github.com/X8/CocoaMarkdown/tree/feature/SupportImageTag

I'll try to find some time to refactor it and remove CocoaPods support from CocoaMarkdown itself as @indragiek don't want to have it (and I fully understand this).

**Comment by indragiek** [comment]
@krodak Very cool! After refactoring, please feel free to send a pull request. Looking forward to reviewing it!

**Comment by mjstallard** [comment]
@krodak I agree with @indragiek - this would be great to see, hope you get chance to refactor!

**Comment by krodak** [comment]
@mjstallard I still work on the feature, have few more bugs fixed, you can track it and fork it from my development branch. 

I'll refactor it after https://github.com/indragiek/CocoaMarkdown/pull/20 is accepted, to be sure that my approach is consistent with current CM implementation. 

@mjstallard I'll let you know when it's finished.

**Comment by albertbori** [comment]
Any update on this? Images are crucial markdown feature for my project.

**Comment by indragiek** [comment]
@krodak #20 has been merged.

**Comment by cpowers** [comment]
@krodak Any plans on finishing this integration? It would be a very nice feature.

**Comment by ianbytchek** [comment]
@krodak :clap: @krodak :clap: @krodak :clap:

**Comment by indragiek** [comment]
Image support has been implemented in #49 thanks to @jlj!
