### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by szl-926929** [indragiek/CocoaMarkdown#15]
how to build ? cmark is empty!!!

**Comment by indragiek** [comment]
cmark is a submodule so you need to check out the submodules before trying to build:

```
cd <repo directory>
git submodule update --init --recursive
```

**Comment by szl-926929** [comment]
thanks，build success。but，image can't show。is bug? or it is my problem?

**Comment by indragiek** [comment]
Support for images hasn't been implemented yet. See #10

**Comment by nico75005** [comment]
I'm probably doing something wrong but in my case it doesn't work.
With the terminal, I go to my project's root folder, and run:
`git submodule add https://github.com/indragiek/CocoaMarkdown.git`
It works fine. Then `cd CocoaMarkdown` and do `git submodule update --init --recursive`. All the submodules get downloaded, it's fine.

But when I want to actually use CocoaMarkdown, doing a `import CocoaMarkdown` get me a `No such module 'CocoaMarkdown'`.

Importing it in my bridging header doesn't work either: `#import "CocoaMarkdown.h"`
