### ISSUE TITLE
UITextView configuration to allow opening of links

### ISSUE THREAD

**Issue by mjstallard** [indragiek/CocoaMarkdown#21]
Hello!

I'm really excited by the possibilities of CocoaMarkdown, especially with an image support PR in progress! I'm trying to integrate it into a project I'm working on, but I'm having trouble getting links to open when tapped as per the example iOS app. I'm probably doing it wrong, but is there something glaringly incorrect with how I've configured this view controller/text view (please excuse the frame setting code :stuck_out_tongue_winking_eye: )?

```swift
import UIKit
import CocoaMarkdown

class Wat: UIViewController {
    let textView = UITextView(frame: CGRect(x: 0, y: 0, width: 320, height: 500))
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(textView)
        
        let path = NSBundle.mainBundle().pathForResource("test", ofType: "md")!
        let document = CMDocument(contentsOfFile: path, options: .Smart)
        let renderer = CMAttributedStringRenderer(document: document, attributes: CMTextAttributes())
        textView.attributedText = renderer.render()
    }
}
```

Note that the link does render as blue and underlined, but is not tappable.

**Comment by mjstallard** [comment]
Think I have it working now! Turns out that you have to ensure that the `UITextView` is `selectable`. Otherwise, no dice..

**Comment by indragiek** [comment]
@mjstallard Hi Mike, that's correct, `selectable` has to be enabled. Sorry I couldn't respond quicker!
