### ISSUE TITLE
Convert Markdown from String not File

### ISSUE THREAD

**Issue by talezion** [indragiek/CocoaMarkdown#24]
Hi, 

Is there a way to convert Markdown directly from String instead of creating CMDocument? The reason is I have the markdown text in a String, so I need to save to local directory and then convert to CMDocument which is an expensive task. CMDocument can only take contentOfFile.

Thank you
Tal

**Comment by indragiek** [comment]
You can use `-[CMDocument initWithData:options:]`. For an `NSString` you have to convert it into an `NSData` first:

```
// Use appropriate encoding here
NSData *data = [string dataUsingEncoding:NSUTF8StringEncoding];
CMDocument *doc = [[CMDocument alloc] initWithData:data options:0];
```

**Comment by albertbori** [comment]
+1 Would be nice to have a convenience initializer.

**Comment by indragiek** [comment]
A convenience initializer was added as part of #52.
