### ISSUE TITLE
Set image width to 100% when rendering HTML

### ISSUE THREAD

**Issue by MaxIsMyName** [indragiek/CocoaMarkdown#26]
I added code to make images' width scale to fit the web page when rendering the markdown to HTML, would this be of any interest for anyone ? I could make a PR if so.

**Comment by ZHAOTING** [comment]
@SASDOE Hi, this feature is needed in my app. It would be appreciated if you could make a PR.

**Comment by indragiek** [comment]
I'm going to close this issue since it's not a bug, if you want to contribute the enhancement as a PR that would be welcome.
