### ISSUE TITLE
Cocoapods install issue: 'cmark.h' file not found

### ISSUE THREAD

**Issue by albertbori** [indragiek/CocoaMarkdown#27]
Steps to reproduce:
1) Install cmake
2) Install cocoapods
3) Clone this [project](https://github.com/albertbori/MarkdownTest)
4) Navigate to the project directory and run `pod install`
5) Open the `MarkdownTest.xcworkspace` (Xcode 7.2.1)
6) Build project

Expected results: The project should build without errors

Actual results: The project fails to build with the error: 
```
/Users/me/dev/MarkdownTest/Pods/CocoaMarkdown/CocoaMarkdown/CMNode_Private.h:10:9:
'cmark.h' file not found
```

**Comment by albertbori** [comment]
Verified fixed.

**Comment by rizwan95** [comment]
Thanks for the fix @Frugghi and @albertbori. Thanks for the merge, @indragiek 

Looks like the repo doesn't update the recent changes in cocoapods, yet.

Anyone who wants to use this awesome framework, please use the path https://github.com/LetaiefAymen/CocoaMarkdown.git until the authors make the changes in the podspec.


Example
` pod "CocoaMarkdown", :git => 'https://github.com/LetaiefAymen/CocoaMarkdown.git'`
