### ISSUE TITLE
Some README code doesn't compile

### ISSUE THREAD

**Issue by ghost** [indragiek/CocoaMarkdown#33]
Hello.

The README includes several references to code that sends nil for the options. But that parameter is a required one so it doesn't compile:

`let document = CMDocument(contentsOfFile: path, options: nil)`

Maybe I'm missing something?

**Comment by indragiek** [comment]
That was a change that happened in a later version of swift. Now you pass `[]` instead of `nil` to represent an empty option set.

**Comment by indragiek** [comment]
I'll leave this open to remind myself to fix the references in the README.

**Comment by sraposa** [comment]
Cool. Thx for quick reply.
