### ISSUE TITLE
Umbrella header for a framework build generates warnings in Xcode 7.3.1 (iOS framework build)

### ISSUE THREAD

**Issue by blackfog** [indragiek/CocoaMarkdown#34]
<module-includes>:1:1: warning: umbrella header for module 'CocoaMarkdown' does not include header 'Ono.h' [-Wincomplete-umbrella]
# import "Headers/CocoaMarkdown.h"

^
<module-includes>:1:1: warning: umbrella header for module 'CocoaMarkdown' does not include header 'ONOXMLDocument.h' [-Wincomplete-umbrella]
2 warnings generated.
2 warnings generated.

**Comment by blackfog** [comment]
<path>/<module-includes>:1:1: Umbrella header for module 'CocoaMarkdown' does not include header 'Ono.h'

<path>/<module-includes>:1:1: Umbrella header for module 'CocoaMarkdown' does not include header 'ONOXMLDocument.h'

**Comment by sraposa** [comment]
Same here.   The other warning I get is "ONOXMLDocument.m:349:23: 'enumerateElementsWithCSS:block:' is deprecated.

**Comment by indragiek** [comment]
The umbrella header warning no longer reproduces on a recent Xcode version (11/12), closing this for now, feel free to open a new issue if this happens again.
