### ISSUE TITLE
CocoaPods not support

### ISSUE THREAD

**Issue by cooler333** [indragiek/CocoaMarkdown#39]
https://cocoapods.org/?q=CocoaMarkdown

SORRY. NO PODS FOUND.

**Comment by jgrandelli** [comment]
Looks like https://github.com/indragiek/CocoaMarkdown/pull/20 added the pod spec. To support cocoa pods you would need to actually push the pod to trunk & create tags for releases. I would add a PR for this but thats not something you can do via a PR. If you would prefer not to manage the actual cocoapod, myself or anyone on the URBN Mobile Team would be happy to do so. We would need to have access to push tags this repo and could setup the pod in the trunk for you.

Dealing with the Cocoapods trunk:
https://guides.cocoapods.org/making/getting-setup-with-trunk.html
