### ISSUE TITLE
provide -[CMDocument attributedString]

### ISSUE THREAD

**Issue by dinhviethoa** [indragiek/CocoaMarkdown#4]
It would be an easy to way to render a MarkDown document to a NSTextView.

**Comment by indragiek** [comment]
I'm not sure this one is worth adding, as doing it currently only requires 2-3 lines of code (see the example in the README). I think most people would want to customize the attributes used in the attributed string, so having a single method that just returns the attributed string using the defaults probably wouldn't be super useful.

**Comment by indragiek** [comment]
I think this is a reasonable compromise :)

**Comment by dinhviethoa** [comment]
Looks perfect!  

--  
Hoa V. Dinh
