### ISSUE TITLE
CocoaMarkdown does not compile on Sierra using /Applications/Xcode-beta 2.app/Contents/Developer

### ISSUE THREAD

**Issue by ayercm** [indragiek/CocoaMarkdown#40]
Installing cmark (0.21.0)
[!] /bin/bash -c 
set -e
echo `pwd`
sed -i '' 's/include <\(cmark.*\)>/include "\1"/' src/cmark.h
mkdir -p build; cd build && cmake -G Xcode ..

/Users/colinayer2/Library/Caches/CocoaPods/Pods/Release/cmark/0.21.0-0868a
-- The C compiler identification is AppleClang 8.0.0.8000040
-- The CXX compiler identification is AppleClang 8.0.0.8000040
-- Configuring incomplete, errors occurred!
See also "/Users/colinayer2/Library/Caches/CocoaPods/Pods/Release/cmark/0.21.0-0868a/build/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.

**Comment by ishaanSejwal** [comment]
Hey @ayercm were you able to solve this? Would love to know how you did. I have checked my CMakeOutput.log file and see that the build succeeded and it was able to find the correct C/CXX compiler after compiler identification source compilation succeeded.
