### ISSUE TITLE
Parser does not detect \r newline characters

### ISSUE THREAD

**Issue by damienrambout** [indragiek/CocoaMarkdown#7]
When parsing a string composed of `\r` characters, the parser continue parsing as if no newline character was detected. (e.g. Second `*` list bullet character will be rendered as `*` because no newline was detected).

The final result is weird because a `UILabel` or `UITextView` will detect newlines, but the whole attributed string will be messed up.

I know using `\r` characters is never a good idea, but sometimes that's the only thing you get from a remote server...

**Comment by indragiek** [comment]
The parser used by CocoaMarkdown is the C reference implementation of [CommonMark](https://github.com/jgm/CommonMark), so this should be reported there instead. 

As an easy workaround, you could replace `\r` with `\n` yourself before passing the string to the parser.
