### ISSUE TITLE
Better code block

### ISSUE THREAD

**Issue by jamztang** [indragiek/CocoaMarkdown#9]
Is there plans for syntax highlighting, and even potential inline scroll instead of word wrapping?

**Comment by indragiek** [comment]
A full syntax highlighter could be an entire project of its own, but if you want to contribute something that provides a module for integrating Markdown with syntax highlighting then that would certainly be welcome.

**Comment by albertbori** [comment]
I agree with @indragiek. It is far beyond the scope of CocoaMarkdown to provide that functionality. If you convert to html, you can always import javascript libraries that give that functionality and show it in a `UIWebView`.

If you want to implement your own custom syntax highlighting for attributed strings, you can add your own identifying attributes and then use them to manipulate the resulting attributed string.

Example:
```
let attributes = CMTextAttributes()
attributes.codeBlockAttributes = [
    "elementType": "codeBlock"
]
let attributedString = CMAttributedStringRenderer(document: document, attributes: attributes).render()
attributedString.enumerateAttributesInRange(NSRange(location: 0, length: attributedString.length), options: NSAttributedStringEnumerationOptions.LongestEffectiveRangeNotRequired) { (attributes, range, stopPointer) in
    if attributes["elementType"] as? String == "codeBlock" {
        //this text is in a code block
    }
}
```

**Comment by indragiek** [comment]
@albertbori That's a nice solution! I'm going to close this issue under the conclusion that it's out of the scope of the project.
